import type { AuditLogEntry, RetentionConfig, AccessPolicyEntry } from "@/modules/audit-compliance/types";

export function getAuditLogEntries(): AuditLogEntry[] {
  return [
    {
      id: "audit-001",
      eventId: "evt-audit-001",
      actor: "Kwame Asante",
      actorRole: "super_admin",
      category: "admin_access",
      action: "change_admin_role",
      riskLevel: "critical",
      entityId: "admin-007",
      entityType: "admin_account",
      entityLabel: "Fatima Al-Hassan (reviewer → finance)",
      summary: "Kwame Asante promoted Fatima Al-Hassan from reviewer to finance role.",
      outcome: "success",
      timestamp: "2026-04-18T14:32:11Z",
      note: "Finance team expansion approved by ops lead.",
      metadata: { previousRole: "reviewer", newRole: "finance", approvedBy: "Kwame Asante" },
    },
    {
      id: "audit-002",
      eventId: "evt-audit-002",
      actor: "Kwame Asante",
      actorRole: "super_admin",
      category: "admin_access",
      action: "invite_admin",
      riskLevel: "critical",
      entityId: "admin-008",
      entityType: "admin_account",
      entityLabel: "samuel.osei@travelmate.test (operations)",
      summary: "Kwame Asante sent admin invite to samuel.osei@travelmate.test with operations role.",
      outcome: "success",
      timestamp: "2026-04-17T09:15:44Z",
      note: "New operations hire onboarding.",
      metadata: { invitedEmail: "samuel.osei@travelmate.test", assignedRole: "operations" },
    },
    {
      id: "audit-003",
      eventId: "evt-audit-003",
      actor: "Amara Nwosu",
      actorRole: "operations",
      category: "verification",
      action: "approve_verification",
      riskLevel: "high",
      entityId: "partner-201",
      entityType: "partner",
      entityLabel: "GlobalStays Ltd",
      summary: "Amara Nwosu approved verification for GlobalStays Ltd, promoting partner lifecycle to verified.",
      outcome: "success",
      timestamp: "2026-04-17T11:04:22Z",
      note: "All KYC/KYB documents reviewed and confirmed valid.",
      metadata: { verificationId: "verif-201", previousStatus: "in_review", newStatus: "approved" },
    },
    {
      id: "audit-004",
      eventId: "evt-audit-004",
      actor: "Amara Nwosu",
      actorRole: "operations",
      category: "verification",
      action: "reject_verification",
      riskLevel: "high",
      entityId: "partner-214",
      entityType: "partner",
      entityLabel: "QuickRide Kenya",
      summary: "Amara Nwosu rejected verification for QuickRide Kenya due to mismatched business registration documents.",
      outcome: "success",
      timestamp: "2026-04-16T15:50:09Z",
      note: "Business registration name does not match submitted ID. Partner notified to re-submit.",
      metadata: { verificationId: "verif-214", rejectionReason: "document_mismatch", previousStatus: "in_review" },
    },
    {
      id: "audit-005",
      eventId: "evt-audit-005",
      actor: "Kwame Asante",
      actorRole: "super_admin",
      category: "partner_lifecycle",
      action: "suspend_partner",
      riskLevel: "critical",
      entityId: "partner-198",
      entityType: "partner",
      entityLabel: "RapidTransfer EA",
      summary: "Kwame Asante suspended partner RapidTransfer EA following fraud risk escalation.",
      outcome: "success",
      timestamp: "2026-04-16T08:22:37Z",
      note: "Multiple fraud risk flags triggered by payout and listing anomaly detection. Suspension pending investigation.",
      metadata: { previousLifecycle: "verified", triggerSource: "fraud_risk_flag", incidentRef: "INC-2026-0041" },
    },
    {
      id: "audit-006",
      eventId: "evt-audit-006",
      actor: "Amara Nwosu",
      actorRole: "operations",
      category: "partner_lifecycle",
      action: "lock_partner",
      riskLevel: "high",
      entityId: "partner-177",
      entityType: "partner",
      entityLabel: "Nairobi Hotels Collective",
      summary: "Amara Nwosu locked partner account Nairobi Hotels Collective pending compliance review.",
      outcome: "success",
      timestamp: "2026-04-15T13:41:58Z",
      note: "Account locked to prevent further changes while compliance review is in progress.",
      metadata: { reason: "compliance_review", reviewRef: "CR-2026-0088" },
    },
    {
      id: "audit-007",
      eventId: "evt-audit-007",
      actor: "Priya Sharma",
      actorRole: "reviewer",
      category: "listing_moderation",
      action: "emergency_unpublish",
      riskLevel: "critical",
      entityId: "listing-3041",
      entityType: "listing",
      entityLabel: "Serengeti Camp Suite (stay)",
      summary: "Priya Sharma emergency-unpublished listing Serengeti Camp Suite due to reported safety concern.",
      outcome: "success",
      timestamp: "2026-04-15T10:08:14Z",
      note: "Reported safety concern by guest team. Listing taken down immediately pending partner review.",
      metadata: { listingType: "stay", reportSource: "guest_escalation", incidentRef: "INC-2026-0039" },
    },
    {
      id: "audit-008",
      eventId: "evt-audit-008",
      actor: "Priya Sharma",
      actorRole: "reviewer",
      category: "listing_moderation",
      action: "reject_listing",
      riskLevel: "medium",
      entityId: "listing-3085",
      entityType: "listing",
      entityLabel: "Dubious Deluxe Room (stay)",
      summary: "Priya Sharma rejected listing Dubious Deluxe Room for policy violations: misleading media and inaccurate amenity claims.",
      outcome: "success",
      timestamp: "2026-04-14T16:29:33Z",
      note: "Listing content did not meet content policy standards. Partner notified with correction guidance.",
      metadata: { rejectionReason: "content_policy_violation", listingType: "stay", correctionRequired: "true" },
    },
    {
      id: "audit-009",
      eventId: "evt-audit-009",
      actor: "Priya Sharma",
      actorRole: "reviewer",
      category: "listing_moderation",
      action: "approve_listing",
      riskLevel: "low",
      entityId: "listing-3092",
      entityType: "listing",
      entityLabel: "Lakeside Airport Transfer (transfer)",
      summary: "Priya Sharma approved listing Lakeside Airport Transfer for live status.",
      outcome: "success",
      timestamp: "2026-04-14T11:55:02Z",
      note: "All compliance checks passed. Vehicle class and route information verified.",
      metadata: { listingType: "transfer", vehicleClass: "sedan" },
    },
    {
      id: "audit-010",
      eventId: "evt-audit-010",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "financial",
      action: "update_commission_rule",
      riskLevel: "high",
      entityId: "commission-rule-04",
      entityType: "commission_rule",
      entityLabel: "East Africa stays — standard tier",
      summary: "Tunde Adebayo updated commission rule for East Africa stays standard tier from 12% to 10.5%.",
      outcome: "success",
      timestamp: "2026-04-13T09:44:18Z",
      note: "Rate reduction approved by finance head for Q2 partner retention incentive.",
      metadata: { previousRate: "12%", newRate: "10.5%", region: "East Africa", approvalRef: "FIN-2026-0112" },
    },
    {
      id: "audit-011",
      eventId: "evt-audit-011",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "financial",
      action: "update_service_fee",
      riskLevel: "high",
      entityId: "fee-rule-02",
      entityType: "commission_rule",
      entityLabel: "Transfer bookings — platform service fee",
      summary: "Tunde Adebayo updated platform service fee for transfer bookings from 3.5% to 4%.",
      outcome: "success",
      timestamp: "2026-04-12T14:10:55Z",
      note: "Service fee adjustment reflects updated payment processing cost structure.",
      metadata: { previousFee: "3.5%", newFee: "4%", bookingType: "transfer", approvalRef: "FIN-2026-0109" },
    },
    {
      id: "audit-012",
      eventId: "evt-audit-012",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "financial",
      action: "manual_adjustment",
      riskLevel: "high",
      entityId: "partner-201",
      entityType: "partner",
      entityLabel: "GlobalStays Ltd",
      summary: "Tunde Adebayo applied manual ledger adjustment of +$320.00 to GlobalStays Ltd for disputed booking correction.",
      outcome: "success",
      timestamp: "2026-04-11T10:33:47Z",
      note: "Correction for overbilling on booking BK-2026-0812 confirmed by partner escalation review.",
      metadata: { adjustmentAmount: "+$320.00", currency: "USD", bookingRef: "BK-2026-0812", approvalRef: "FIN-2026-0104" },
    },
    {
      id: "audit-013",
      eventId: "evt-audit-013",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "settlement",
      action: "trigger_settlement_run",
      riskLevel: "high",
      entityId: "settlement-run-047",
      entityType: "settlement",
      entityLabel: "Settlement run #047 — April W2",
      summary: "Tunde Adebayo triggered settlement run #047 for April W2, covering 38 completed bookings.",
      outcome: "success",
      timestamp: "2026-04-10T08:00:00Z",
      note: "Scheduled April W2 settlement run initiated on time.",
      metadata: { runId: "settlement-run-047", bookingCount: "38", period: "April W2 2026" },
    },
    {
      id: "audit-014",
      eventId: "evt-audit-014",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "settlement",
      action: "place_settlement_hold",
      riskLevel: "critical",
      entityId: "settlement-run-047",
      entityType: "settlement",
      entityLabel: "Settlement run #047 — GlobalStays Ltd payout",
      summary: "Tunde Adebayo placed settlement hold on GlobalStays Ltd payout in run #047 pending payout account re-verification.",
      outcome: "success",
      timestamp: "2026-04-10T09:15:22Z",
      note: "Payout hold required: finance flagged account change within risk window. Re-verification pending.",
      metadata: { runId: "settlement-run-047", partnerId: "partner-201", holdReason: "account_change_risk_window" },
    },
    {
      id: "audit-015",
      eventId: "evt-audit-015",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "settlement",
      action: "process_refund",
      riskLevel: "high",
      entityId: "refund-0088",
      entityType: "settlement",
      entityLabel: "Refund BK-2026-0791 — RapidTransfer EA",
      summary: "Tunde Adebayo processed refund for booking BK-2026-0791 after partner acknowledged cancellation obligation.",
      outcome: "success",
      timestamp: "2026-04-09T15:44:11Z",
      note: "Partner acknowledged refund obligation. Refund disbursed to guest.",
      metadata: { bookingRef: "BK-2026-0791", refundAmount: "$180.00", currency: "USD", partnerId: "partner-198" },
    },
    {
      id: "audit-016",
      eventId: "evt-audit-016",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "payout_review",
      action: "approve_payout_method",
      riskLevel: "high",
      entityId: "payout-method-301",
      entityType: "payout_method",
      entityLabel: "GlobalStays Ltd — bank account ending 4421",
      summary: "Tunde Adebayo approved payout method for GlobalStays Ltd after completing identity and account verification.",
      outcome: "success",
      timestamp: "2026-04-08T11:22:05Z",
      note: "Account details verified. No risk flags. Settlement holds released.",
      metadata: { maskedAccount: "****4421", bankName: "Equity Bank", countryCode: "KE" },
    },
    {
      id: "audit-017",
      eventId: "evt-audit-017",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "payout_review",
      action: "reject_payout_method",
      riskLevel: "high",
      entityId: "payout-method-318",
      entityType: "payout_method",
      entityLabel: "QuickRide Kenya — bank account ending 9902",
      summary: "Tunde Adebayo rejected payout method for QuickRide Kenya: account name mismatch with registered business.",
      outcome: "success",
      timestamp: "2026-04-07T14:03:39Z",
      note: "Account holder name does not match verified business registration. Partner notified to re-submit.",
      metadata: { maskedAccount: "****9902", rejectionReason: "account_name_mismatch" },
    },
    {
      id: "audit-018",
      eventId: "evt-audit-018",
      actor: "Tunde Adebayo",
      actorRole: "finance",
      category: "payout_review",
      action: "toggle_payout_settlement_hold",
      riskLevel: "critical",
      entityId: "payout-method-301",
      entityType: "payout_method",
      entityLabel: "GlobalStays Ltd — manual settlement hold",
      summary: "Tunde Adebayo toggled manual settlement hold ON for GlobalStays Ltd payout method during fraud risk investigation.",
      outcome: "success",
      timestamp: "2026-04-06T09:50:28Z",
      note: "Rapid account change pattern detected within 72-hour risk window. Hold placed pending re-verification.",
      metadata: { holdState: "active", riskSignal: "rapid_account_change", riskWindowHours: "72" },
    },
    {
      id: "audit-019",
      eventId: "evt-audit-019",
      actor: "Amara Nwosu",
      actorRole: "operations",
      category: "api_governance",
      action: "revoke_api_key",
      riskLevel: "high",
      entityId: "api-client-088",
      entityType: "api_client",
      entityLabel: "TravelAggregator Pro — API key revoked",
      summary: "Amara Nwosu revoked API key for TravelAggregator Pro following rate-limit abuse pattern.",
      outcome: "success",
      timestamp: "2026-04-05T16:12:44Z",
      note: "Client exceeded rate limits repeatedly and did not respond to warning. Key revoked pending plan review.",
      metadata: { clientId: "api-client-088", abusePattern: "rate_limit_exceeded", violationCount: "7" },
    },
    {
      id: "audit-020",
      eventId: "evt-audit-020",
      actor: "Kwame Asante",
      actorRole: "super_admin",
      category: "api_governance",
      action: "block_api_client",
      riskLevel: "critical",
      entityId: "api-client-102",
      entityType: "api_client",
      entityLabel: "UnknownAggregator — API client blocked",
      summary: "Kwame Asante blocked API client UnknownAggregator for unauthorized data scraping behavior.",
      outcome: "success",
      timestamp: "2026-04-04T12:07:55Z",
      note: "Systematic scraping pattern identified. Client blocked. Legal notified.",
      metadata: { clientId: "api-client-102", blockReason: "unauthorized_scraping", legalNotified: "true" },
    },
  ];
}

export function getRetentionConfig(): RetentionConfig {
  return {
    defaultRetentionDays: 365,
    highRiskRetentionDays: 730,
    criticalRetentionDays: 1825,
    legalHoldEnabled: false,
    lastReviewedAt: "2026-01-15T00:00:00Z",
  };
}

export function getAccessPolicyEntries(): AccessPolicyEntry[] {
  return [
    {
      role: "super_admin",
      canExport: true,
      canViewRetention: true,
      canViewAccessPolicy: true,
      restrictedCategories: [],
    },
    {
      role: "operations",
      canExport: true,
      canViewRetention: false,
      canViewAccessPolicy: true,
      restrictedCategories: [],
    },
    {
      role: "finance",
      canExport: true,
      canViewRetention: false,
      canViewAccessPolicy: false,
      restrictedCategories: ["admin_access"],
    },
    {
      role: "reviewer",
      canExport: false,
      canViewRetention: false,
      canViewAccessPolicy: false,
      restrictedCategories: ["admin_access", "financial", "settlement", "payout_review"],
    },
    {
      role: "support",
      canExport: false,
      canViewRetention: false,
      canViewAccessPolicy: false,
      restrictedCategories: ["admin_access", "financial", "settlement", "payout_review"],
    },
  ];
}
