import type { FinancialOpsRecord } from "@/modules/financial-ops/types";

export function getFinancialOpsRecords(): FinancialOpsRecord[] {
  return [
    {
      id: "fin-001",
      title: "Settlement run failed for Nairobi premium-stay payout batch",
      summary: "A finance-run payout batch failed after 3 completed stay bookings fell out of the reconciliation window.",
      partnerName: "Safari Crest Residences",
      bookingReference: "BK-2026-1142",
      supplyType: "stay",
      region: "East Africa",
      currency: "USD",
      owner: "Tunde Adebayo",
      settlementPeriodLabel: "April W3 2026",
      partnerSettlementStatus: "failed",
      adminRunStatus: "failed",
      refundStatus: null,
      netPayoutAmount: 1840,
      expectedPayoutAmount: 2015,
      reconciliationDeltaAmount: -175,
      failedBookingCount: 3,
      riskWindowLabel: "48-hour settlement risk window",
      failureReason: "Payout batch halted after three completion records missed the settlement aggregation snapshot.",
      operationalNote: "Retry once booking completion evidence is reconciled and the run delta is documented.",
      linkedContext: [
        { id: "fin-ctx-001", label: "Partner account · Safari Crest Residences", href: "/partners?partner=partner-001", statusLabel: "verified", kind: "partner" },
        { id: "fin-ctx-002", label: "Commercial controls · East Africa stays", href: "/commercial-controls?rule=rule-001", statusLabel: "active", kind: "commercial" },
      ],
      evidence: [
        { id: "fin-ev-001", label: "Expected payout", value: "$2,015.00", tone: "info" },
        { id: "fin-ev-002", label: "Run delta", value: "-$175.00", tone: "danger" },
        { id: "fin-ev-003", label: "Failed bookings", value: "3 bookings", tone: "warning" },
      ],
      statements: [],
      activity: [
        {
          id: "fin-act-001",
          title: "Settlement run failed",
          detail: "Finance flagged the failed payout batch after reconciliation totals fell outside the approved risk window.",
          time: "09:20 UTC",
          tone: "danger",
        },
      ],
    },
    {
      id: "fin-002",
      title: "Refund follow-up pending for cancelled airport transfer",
      summary: "Partner refund confirmation is still outstanding after a cancelled transfer booking moved into reverse-settlement review.",
      partnerName: "MetroRide Executive",
      bookingReference: "BK-2026-0791",
      supplyType: "transfer",
      region: "West Africa",
      currency: "USD",
      owner: "Tunde Adebayo",
      settlementPeriodLabel: "April W2 2026",
      partnerSettlementStatus: "reversed",
      adminRunStatus: "partial",
      refundStatus: "requested",
      netPayoutAmount: 0,
      expectedPayoutAmount: 180,
      reconciliationDeltaAmount: -180,
      failedBookingCount: 1,
      riskWindowLabel: "Refund recovery escalation window",
      failureReason: "Refund reversal is still waiting for partner acknowledgement and finance recovery confirmation.",
      operationalNote: "Notify partner first, then track refund recovery before closing reconciliation.",
      linkedContext: [
        { id: "fin-ctx-003", label: "Support & Incidents · refund dispute", href: "/support-incidents?case=sup-002", statusLabel: "monitoring", kind: "support" },
        { id: "fin-ctx-004", label: "Partner account · MetroRide Executive", href: "/partners?partner=partner-004", statusLabel: "verified", kind: "partner" },
      ],
      evidence: [
        { id: "fin-ev-004", label: "Refund amount", value: "$180.00", tone: "warning" },
        { id: "fin-ev-005", label: "Partner-facing status", value: "reversed", tone: "danger" },
        { id: "fin-ev-006", label: "Run state", value: "partial", tone: "warning" },
      ],
      statements: [
        {
          id: "fin-st-001",
          fileName: "travelmate-statement-metroride-april-w2.pdf",
          generatedAt: "2026-04-18T11:10:00Z",
          actor: "Tunde Adebayo",
          status: "generated",
        },
      ],
      activity: [
        {
          id: "fin-act-002",
          title: "Refund follow-up opened",
          detail: "Finance opened a refund recovery trail after the cancelled transfer moved into reverse settlement handling.",
          time: "11:10 UTC",
          tone: "warning",
        },
      ],
    },
    {
      id: "fin-003",
      title: "Completed payout ready for partner statement delivery",
      summary: "A balanced stay settlement completed successfully and is ready for statement generation.",
      partnerName: "Lagoon Suites",
      bookingReference: "BK-2026-1320",
      supplyType: "stay",
      region: "West Africa",
      currency: "USD",
      owner: "Tunde Adebayo",
      settlementPeriodLabel: "April W3 2026",
      partnerSettlementStatus: "paid",
      adminRunStatus: "completed",
      refundStatus: null,
      netPayoutAmount: 960,
      expectedPayoutAmount: 960,
      reconciliationDeltaAmount: 0,
      failedBookingCount: 0,
      riskWindowLabel: "Standard weekly settlement",
      failureReason: null,
      operationalNote: "Generate the statement so partner-facing payout records stay aligned with the completed run.",
      linkedContext: [
        { id: "fin-ctx-005", label: "Partner account · Lagoon Suites", href: "/partners?partner=partner-010", statusLabel: "verified", kind: "partner" },
        { id: "fin-ctx-006", label: "Payout review · verified payout method", href: "/payout-review", statusLabel: "approved", kind: "payout_review" },
      ],
      evidence: [
        { id: "fin-ev-007", label: "Expected payout", value: "$960.00", tone: "success" },
        { id: "fin-ev-008", label: "Run delta", value: "$0.00", tone: "success" },
        { id: "fin-ev-009", label: "Statement status", value: "pending generation", tone: "info" },
      ],
      statements: [],
      activity: [
        {
          id: "fin-act-003",
          title: "Settlement completed",
          detail: "The payout batch closed with a clean reconciliation result and no refund exposure.",
          time: "08:05 UTC",
          tone: "success",
        },
      ],
    },
    {
      id: "fin-004",
      title: "Refund dispute recovered after partner acknowledgment",
      summary: "A previously disputed refund has been recovered and the reconciliation gap is now balanced.",
      partnerName: "Desert Pearl Transfers",
      bookingReference: "BK-2026-0615",
      supplyType: "transfer",
      region: "Gulf",
      currency: "USD",
      owner: "Amina Bello",
      settlementPeriodLabel: "April W1 2026",
      partnerSettlementStatus: "reversed",
      adminRunStatus: "completed",
      refundStatus: "recovered",
      netPayoutAmount: 0,
      expectedPayoutAmount: 0,
      reconciliationDeltaAmount: 0,
      failedBookingCount: 0,
      riskWindowLabel: "Recovered refund trail",
      failureReason: null,
      operationalNote: "Recovered refund trail retained for audit visibility.",
      linkedContext: [
        { id: "fin-ctx-007", label: "Support & Incidents · listing sync case", href: "/support-incidents?case=sup-003", statusLabel: "escalated", kind: "support" },
        { id: "fin-ctx-008", label: "Partner account · Desert Pearl Transfers", href: "/partners?partner=partner-008", statusLabel: "verified", kind: "partner" },
      ],
      evidence: [
        { id: "fin-ev-010", label: "Refund trail", value: "recovered", tone: "success" },
        { id: "fin-ev-011", label: "Run delta", value: "$0.00", tone: "success" },
        { id: "fin-ev-012", label: "Audit readiness", value: "complete", tone: "info" },
      ],
      statements: [
        {
          id: "fin-st-002",
          fileName: "travelmate-statement-desertpearl-april-w1.pdf",
          generatedAt: "2026-04-12T14:00:00Z",
          actor: "Amina Bello",
          status: "generated",
        },
      ],
      activity: [
        {
          id: "fin-act-004",
          title: "Refund recovered",
          detail: "Finance confirmed partner acknowledgment and recovered the disputed refund through the reconciliation trail.",
          time: "14:00 UTC",
          tone: "success",
        },
      ],
    },
  ];
}
