import type { VerificationCase } from "@/modules/verification-review/types";

export const verificationCasesSeed: VerificationCase[] = [
  {
    id: "verify-001",
    partnerName: "Amina Yusuf",
    businessName: "North Harbour Stays",
    submittedAt: "2026-04-17T08:10:00.000Z",
    country: "Nigeria",
    riskLevel: "high",
    verificationStatus: "pending",
    lifecycleState: "pending",
    noteDraft: "Passport image is clear, but business registration needs a secondary check.",
    notificationSummary: "Decision will notify the partner and update the verification tracker in partner_app.",
    documents: [
      {
        id: "doc-1",
        label: "Passport",
        fileName: "amina-yusuf-passport.pdf",
        documentType: "identity",
        mimeType: "application/pdf",
        sizeLabel: "2.4 MB",
        pageCount: 2,
        uploadedAt: "2026-04-17T08:11:00.000Z",
        source: "partner_portal",
        previewPath: "/api/backend/verification-cases/verify-001/documents/doc-1/view",
        securePath: "/api/backend/verification-cases/verify-001/documents/doc-1/download",
        previewSummary: "Primary passport page and signature page uploaded from the partner verification wizard.",
        reviewerHint: "Identity document is legible and matches the submitted legal name.",
        status: "received",
      },
      {
        id: "doc-2",
        label: "Business registration",
        fileName: "north-harbour-registration-scan.pdf",
        documentType: "business",
        mimeType: "application/pdf",
        sizeLabel: "3.1 MB",
        pageCount: 4,
        uploadedAt: "2026-04-17T08:12:00.000Z",
        source: "partner_portal",
        previewPath: "/api/backend/verification-cases/verify-001/documents/doc-2/view",
        securePath: "/api/backend/verification-cases/verify-001/documents/doc-2/download",
        previewSummary: "Business certificate packet with registrar stamp, director listing, and filing reference pages.",
        reviewerHint: "Secondary manual check needed because the registrar stamp is partially obscured on page 3.",
        status: "flagged",
      },
      {
        id: "doc-3",
        label: "Utility bill",
        fileName: "north-harbour-address-proof.jpg",
        documentType: "address",
        mimeType: "image/jpeg",
        sizeLabel: "1.2 MB",
        pageCount: 1,
        uploadedAt: "2026-04-17T08:13:00.000Z",
        source: "partner_portal",
        previewPath: "/api/backend/verification-cases/verify-001/documents/doc-3/view",
        securePath: "/api/backend/verification-cases/verify-001/documents/doc-3/download",
        previewSummary: "Single-page electricity bill used to verify registered operating address.",
        reviewerHint: "Address document is current and lines up with the business registration record.",
        status: "received",
      },
    ],
    reviewSignals: {
      flaggedDocumentCount: 1,
      needsMoreInfo: true,
      latestActionLabel: "Submission received",
    },
    operatingCoverage: {
      countries: ["Nigeria"],
      regions: ["Lagos", "Federal Capital Territory"],
      cities: ["Lekki", "Abuja"],
      coverageNotes: "Airport stays require 24-hour advance notice for premium guests.",
    },
    payoutSetup: {
      payoutMethod: "bank_transfer",
      settlementCurrency: "NGN",
      payoutSchedule: "weekly",
      settlementTrigger: "service_completion",
    },
    history: [
      {
        id: "hist-1",
        actor: "System",
        action: "Submission received",
        timestamp: "2026-04-17 08:10 UTC",
        note: "Partner submitted KYC/KYB package from the completed partner verification flow.",
      },
    ],
  },
  {
    id: "verify-002",
    partnerName: "David Mensah",
    businessName: "Accra Executive Transfers",
    submittedAt: "2026-04-17T07:05:00.000Z",
    country: "Ghana",
    riskLevel: "medium",
    verificationStatus: "in_review",
    lifecycleState: "pending",
    noteDraft: "Routing documents look valid. Awaiting confirmation of company tax certificate.",
    notificationSummary: "Request-more-info keeps the partner lifecycle pending and reopens the evidence request loop.",
    documents: [
      {
        id: "doc-4",
        label: "National ID",
        fileName: "david-mensah-national-id.pdf",
        documentType: "identity",
        mimeType: "application/pdf",
        sizeLabel: "1.8 MB",
        pageCount: 2,
        uploadedAt: "2026-04-17T07:06:00.000Z",
        source: "partner_portal",
        previewPath: "/api/backend/verification-cases/verify-002/documents/doc-4/view",
        securePath: "/api/backend/verification-cases/verify-002/documents/doc-4/download",
        previewSummary: "Two-page government ID packet with front and back scans.",
        reviewerHint: "Identity verification passed; no mismatch found on the primary holder details.",
        status: "received",
      },
      {
        id: "doc-5",
        label: "Tax certificate",
        fileName: "accra-executive-tax-certificate.pdf",
        documentType: "compliance",
        mimeType: "application/pdf",
        sizeLabel: "2.9 MB",
        pageCount: 3,
        uploadedAt: "2026-04-17T07:07:00.000Z",
        source: "resubmission",
        previewPath: "/api/backend/verification-cases/verify-002/documents/doc-5/view",
        securePath: "/api/backend/verification-cases/verify-002/documents/doc-5/download",
        previewSummary: "Resubmitted tax certificate packet with watermark, issuing authority seal, and attachment notes.",
        reviewerHint: "Registration number is still not fully visible in the uploaded scan, so more information is required.",
        status: "flagged",
      },
      {
        id: "doc-6",
        label: "Fleet insurance",
        fileName: "fleet-insurance-certificate.pdf",
        documentType: "compliance",
        mimeType: "application/pdf",
        sizeLabel: "2.2 MB",
        pageCount: 5,
        uploadedAt: "2026-04-17T07:08:00.000Z",
        source: "partner_portal",
        previewPath: "/api/backend/verification-cases/verify-002/documents/doc-6/view",
        securePath: "/api/backend/verification-cases/verify-002/documents/doc-6/download",
        previewSummary: "Insurance schedule covering the current fleet allocation and liability window.",
        reviewerHint: "Coverage dates remain valid through the current operating quarter.",
        status: "received",
      },
    ],
    reviewSignals: {
      flaggedDocumentCount: 1,
      needsMoreInfo: true,
      latestActionLabel: "Review started",
    },
    operatingCoverage: {
      countries: ["Ghana"],
      regions: ["Greater Accra", "Ashanti"],
      cities: ["Accra", "Kumasi"],
      coverageNotes: "Late-night transfer coverage is limited to prebooked airport and corporate routes.",
    },
    payoutSetup: {
      payoutMethod: "mobile_money",
      settlementCurrency: "USD",
      payoutSchedule: "daily",
      settlementTrigger: "service_completion",
    },
    history: [
      {
        id: "hist-2",
        actor: "Reviewer lane",
        action: "Review started",
        timestamp: "2026-04-17 07:20 UTC",
        note: "Initial reviewer opened the case and marked it in review.",
      },
    ],
  },
  {
    id: "verify-003",
    partnerName: "Maya Patel",
    businessName: "Savannah Retreat Collections",
    submittedAt: "2026-04-16T19:40:00.000Z",
    country: "Kenya",
    riskLevel: "low",
    verificationStatus: "approved",
    lifecycleState: "verified",
    noteDraft: "Approved after clean KYB match and manual ownership confirmation.",
    notificationSummary: "Suspend remains available as an admin lifecycle control without changing approval history.",
    documents: [
      {
        id: "doc-7",
        label: "Passport",
        fileName: "maya-patel-passport.pdf",
        documentType: "identity",
        mimeType: "application/pdf",
        sizeLabel: "2.1 MB",
        pageCount: 2,
        uploadedAt: "2026-04-16T19:41:00.000Z",
        source: "partner_portal",
        previewPath: "/api/backend/verification-cases/verify-003/documents/doc-7/view",
        securePath: "/api/backend/verification-cases/verify-003/documents/doc-7/download",
        previewSummary: "Clean passport packet captured from the verified owner during onboarding.",
        reviewerHint: "Identity document and ownership confirmation both cleared the manual review lane.",
        status: "received",
      },
      {
        id: "doc-8",
        label: "Company registration",
        fileName: "savannah-retreat-company-registration.pdf",
        documentType: "business",
        mimeType: "application/pdf",
        sizeLabel: "3.4 MB",
        pageCount: 6,
        uploadedAt: "2026-04-16T19:42:00.000Z",
        source: "partner_portal",
        previewPath: "/api/backend/verification-cases/verify-003/documents/doc-8/view",
        securePath: "/api/backend/verification-cases/verify-003/documents/doc-8/download",
        previewSummary: "Full incorporation packet, shareholding summary, and beneficial ownership sheet.",
        reviewerHint: "Corporate registration and beneficial ownership checks completed without exceptions.",
        status: "received",
      },
      {
        id: "doc-9",
        label: "Bank letter",
        fileName: "savannah-retreat-bank-letter.pdf",
        documentType: "banking",
        mimeType: "application/pdf",
        sizeLabel: "1.6 MB",
        pageCount: 1,
        uploadedAt: "2026-04-16T19:43:00.000Z",
        source: "partner_portal",
        previewPath: "/api/backend/verification-cases/verify-003/documents/doc-9/view",
        securePath: "/api/backend/verification-cases/verify-003/documents/doc-9/download",
        previewSummary: "Bank verification letter confirming account ownership and active settlement status.",
        reviewerHint: "Bank letter was used to complete the KYB ownership and settlement readiness checks.",
        status: "received",
      },
    ],
    reviewSignals: {
      flaggedDocumentCount: 0,
      needsMoreInfo: false,
      latestActionLabel: "Verification approved",
    },
    operatingCoverage: {
      countries: ["Kenya"],
      regions: ["Nairobi", "Central"],
      cities: ["Nairobi", "Nakuru"],
      coverageNotes: "Seasonal inventory returns first in Nairobi before countryside retreat inventory is reactivated.",
    },
    payoutSetup: {
      payoutMethod: "bank_transfer",
      settlementCurrency: "GBP",
      payoutSchedule: "manual",
      settlementTrigger: "service_completion",
    },
    history: [
      {
        id: "hist-3",
        actor: "Reviewer lane",
        action: "Verification approved",
        timestamp: "2026-04-16 20:15 UTC",
        note: "Partner verification approved and lifecycle moved to verified.",
      },
    ],
  },
];

export function getVerificationCases() {
  return verificationCasesSeed;
}
