import type { SystemConfigRecord } from "@/modules/system-config/types";

export function getSystemConfigRecords(): SystemConfigRecord[] {
  return [
    // ── Taxonomy items ──────────────────────────────────────────────────────
    {
      id: "sysc-001",
      kind: "taxonomy",
      name: "WiFi",
      slug: "wifi",
      description: "High-speed wireless internet access available across the property.",
      status: "active",
      category: "amenity",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 312,
      updatedBy: "Amina Bello", updatedAt: "2025-11-04T09:00:00Z",
      operationalNote: "Standard amenity. No changes needed.",
      history: [{ id: "sysc-001-h1", actor: "Amina Bello", action: "Published", timestamp: "2025-11-04T09:00:00Z", note: "Initial taxonomy publish for WiFi amenity." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-002",
      kind: "taxonomy",
      name: "Swimming Pool",
      slug: "swimming-pool",
      description: "Outdoor or indoor swimming pool available for guest use.",
      status: "active",
      category: "amenity",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 148,
      updatedBy: "David Cole", updatedAt: "2025-11-10T14:30:00Z",
      operationalNote: "Active and widely used.",
      history: [{ id: "sysc-002-h1", actor: "David Cole", action: "Published", timestamp: "2025-11-10T14:30:00Z", note: "Published after partner onboarding review." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-003",
      kind: "taxonomy",
      name: "Airport Parking",
      slug: "airport-parking",
      description: "Dedicated parking facility with transport links to the nearest airport.",
      status: "draft",
      category: "amenity",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 0,
      updatedBy: "Amina Bello", updatedAt: "2026-01-15T11:00:00Z",
      operationalNote: "Draft pending partner adoption review before publish.",
      history: [{ id: "sysc-003-h1", actor: "Amina Bello", action: "Created draft", timestamp: "2026-01-15T11:00:00Z", note: "Added after partner request review." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-004",
      kind: "taxonomy",
      name: "Sedan",
      slug: "sedan",
      description: "Standard four-door passenger sedan for airport and city transfers.",
      status: "active",
      category: "vehicle_class",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 278,
      updatedBy: "David Cole", updatedAt: "2025-10-20T08:45:00Z",
      operationalNote: "Core vehicle class. Stable.",
      history: [{ id: "sysc-004-h1", actor: "David Cole", action: "Published", timestamp: "2025-10-20T08:45:00Z", note: "Published at platform launch." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-005",
      kind: "taxonomy",
      name: "SUV",
      slug: "suv",
      description: "Sport utility vehicle for group and premium transfer bookings.",
      status: "active",
      category: "vehicle_class",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 193,
      updatedBy: "David Cole", updatedAt: "2025-10-20T08:50:00Z",
      operationalNote: "Active vehicle class.",
      history: [{ id: "sysc-005-h1", actor: "David Cole", action: "Published", timestamp: "2025-10-20T08:50:00Z", note: "Published at platform launch." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-006",
      kind: "taxonomy",
      name: "Electric Vehicle",
      slug: "electric-vehicle",
      description: "Battery-powered electric vehicle for eco-conscious transfer bookings.",
      status: "draft",
      category: "vehicle_class",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 0,
      updatedBy: "Amina Bello", updatedAt: "2026-02-03T10:15:00Z",
      operationalNote: "Draft. Awaiting partner fleet data before activating.",
      history: [{ id: "sysc-006-h1", actor: "Amina Bello", action: "Created draft", timestamp: "2026-02-03T10:15:00Z", note: "Added in response to partner fleet survey results." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-007",
      kind: "taxonomy",
      name: "Villa",
      slug: "villa",
      description: "Standalone residential property with private facilities for exclusive stays.",
      status: "active",
      category: "property_type",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 87,
      updatedBy: "David Cole", updatedAt: "2025-10-22T12:00:00Z",
      operationalNote: "Active property type.",
      history: [{ id: "sysc-007-h1", actor: "David Cole", action: "Published", timestamp: "2025-10-22T12:00:00Z", note: "Published after catalog review." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-008",
      kind: "taxonomy",
      name: "Boutique Hotel",
      slug: "boutique-hotel",
      description: "Small independently operated hotel with distinctive design and personalised service.",
      status: "draft",
      category: "property_type",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 0,
      updatedBy: "Amina Bello", updatedAt: "2026-02-18T09:30:00Z",
      operationalNote: "Draft. Needs partner category mapping validation.",
      history: [{ id: "sysc-008-h1", actor: "Amina Bello", action: "Created draft", timestamp: "2026-02-18T09:30:00Z", note: "Added after supply team request." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-009",
      kind: "taxonomy",
      name: "Family-Friendly",
      slug: "family-friendly",
      description: "Properties or vehicles suited for families travelling with children.",
      status: "deprecated",
      category: "tag",
      area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 54,
      updatedBy: "Amina Bello", updatedAt: "2026-03-01T16:00:00Z",
      operationalNote: "Deprecated in favour of more specific child facility tags.",
      history: [{ id: "sysc-009-h1", actor: "Amina Bello", action: "Deprecated", timestamp: "2026-03-01T16:00:00Z", note: "Replaced by child-friendly-amenities and cot-available tags." }],
      latestAuditRecord: null,
    },

    // ── Feature toggles ─────────────────────────────────────────────────────
    {
      id: "sysc-010",
      kind: "toggle",
      name: "Partner Bulk Upload",
      slug: "partner-bulk-upload",
      description: "Allows partners to submit multiple listings via CSV upload in the partner app.",
      status: "enabled",
      category: null, area: "partner_app", rolloutPercent: 100,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 42,
      updatedBy: "David Cole", updatedAt: "2026-01-08T14:00:00Z",
      operationalNote: "Stable feature. Monitoring upload error rates.",
      history: [{ id: "sysc-010-h1", actor: "David Cole", action: "Enabled", timestamp: "2026-01-08T14:00:00Z", note: "Full rollout after successful staged test with 20 partners." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-011",
      kind: "toggle",
      name: "API Rate Limit v2",
      slug: "api-rate-limit-v2",
      description: "Upgraded per-endpoint rate limiting with burst allowance and adaptive throttling.",
      status: "staged",
      category: null, area: "api", rolloutPercent: 30,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 7,
      updatedBy: "Amina Bello", updatedAt: "2026-02-25T11:00:00Z",
      operationalNote: "Staged at 30 percent. Monitoring p99 latency before full rollout.",
      history: [{ id: "sysc-011-h1", actor: "Amina Bello", action: "Staged", timestamp: "2026-02-25T11:00:00Z", note: "Staged rollout at 30 percent for API client impact assessment." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-012",
      kind: "toggle",
      name: "Dynamic Pricing Engine",
      slug: "dynamic-pricing-engine",
      description: "Enables AI-driven demand-based pricing suggestions for partner listings.",
      status: "disabled",
      category: null, area: "global", rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 0,
      updatedBy: "Amina Bello", updatedAt: "2026-01-20T09:00:00Z",
      operationalNote: "Disabled pending legal review of dynamic pricing disclosure requirements.",
      history: [{ id: "sysc-012-h1", actor: "Amina Bello", action: "Disabled", timestamp: "2026-01-20T09:00:00Z", note: "Disabled after legal flagged pricing transparency compliance requirement." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-013",
      kind: "toggle",
      name: "Admin Audit Export v2",
      slug: "admin-audit-export-v2",
      description: "Upgraded compliance export with structured JSON output and digital signature.",
      status: "enabled",
      category: null, area: "admin_dashboard", rolloutPercent: 100,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 19,
      updatedBy: "David Cole", updatedAt: "2026-03-05T10:30:00Z",
      operationalNote: "Fully deployed. No rollback concerns.",
      history: [{ id: "sysc-013-h1", actor: "David Cole", action: "Enabled", timestamp: "2026-03-05T10:30:00Z", note: "Enabled after audit team confirmed export format compliance." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-014",
      kind: "toggle",
      name: "SMS Notification Channel",
      slug: "sms-notification-channel",
      description: "Enables SMS delivery channel for partner-facing admin notifications.",
      status: "disabled",
      category: null, area: "partner_app", rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 0,
      updatedBy: "David Cole", updatedAt: "2026-01-12T13:45:00Z",
      operationalNote: "Disabled. SMS provider contract not yet finalised.",
      history: [{ id: "sysc-014-h1", actor: "David Cole", action: "Disabled", timestamp: "2026-01-12T13:45:00Z", note: "Held pending SMS gateway contract and partner consent flows." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-015",
      kind: "toggle",
      name: "Regional Supply Heatmap",
      slug: "regional-supply-heatmap",
      description: "Visualises partner supply density by region in the admin dashboard.",
      status: "staged",
      category: null, area: "admin_dashboard", rolloutPercent: 50,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 4,
      updatedBy: "Amina Bello", updatedAt: "2026-03-10T15:00:00Z",
      operationalNote: "Staged at 50 percent for ops team feedback.",
      history: [{ id: "sysc-015-h1", actor: "Amina Bello", action: "Staged", timestamp: "2026-03-10T15:00:00Z", note: "Staged for operations team usability review." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-016",
      kind: "toggle",
      name: "Settlement Auto-Retry",
      slug: "settlement-auto-retry",
      description: "Automatically retries failed settlement runs within a configurable risk window.",
      status: "enabled",
      category: null, area: "api", rolloutPercent: 100,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 36,
      updatedBy: "Amina Bello", updatedAt: "2026-02-14T08:00:00Z",
      operationalNote: "Live. Finance confirmed safe retry window configuration.",
      history: [{ id: "sysc-016-h1", actor: "Amina Bello", action: "Enabled", timestamp: "2026-02-14T08:00:00Z", note: "Enabled after finance signed off on retry risk window parameters." }],
      latestAuditRecord: null,
    },

    // ── Service regions ──────────────────────────────────────────────────────
    {
      id: "sysc-017",
      kind: "region",
      name: "Kenya",
      slug: "kenya",
      description: "Supported country in East Africa. Primary market for TravelMate platform operations.",
      status: "active",
      category: null, area: null, rolloutPercent: null,
      regionType: "country", parentId: null, parentSlug: null,
      timezone: "Africa/Nairobi", currency: "KES",
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 184,
      updatedBy: "Amina Bello", updatedAt: "2025-10-01T08:00:00Z",
      operationalNote: "Primary market. Stable.",
      history: [{ id: "sysc-017-h1", actor: "Amina Bello", action: "Activated", timestamp: "2025-10-01T08:00:00Z", note: "Platform launch region activation." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-018",
      kind: "region",
      name: "United Arab Emirates",
      slug: "uae",
      description: "Supported country in the Gulf region. Secondary expansion market.",
      status: "active",
      category: null, area: null, rolloutPercent: null,
      regionType: "country", parentId: null, parentSlug: null,
      timezone: "Asia/Dubai", currency: "AED",
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 62,
      updatedBy: "Amina Bello", updatedAt: "2025-12-15T10:00:00Z",
      operationalNote: "Expansion market. Growing partner base.",
      history: [{ id: "sysc-018-h1", actor: "Amina Bello", action: "Activated", timestamp: "2025-12-15T10:00:00Z", note: "Activated for Gulf expansion phase." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-019",
      kind: "region",
      name: "Nairobi",
      slug: "nairobi",
      description: "Capital city of Kenya. Highest-density partner and booking volume in the network.",
      status: "active",
      category: null, area: null, rolloutPercent: null,
      regionType: "city", parentId: "sysc-017", parentSlug: "kenya",
      timezone: "Africa/Nairobi", currency: "KES",
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 143,
      updatedBy: "David Cole", updatedAt: "2025-10-01T08:30:00Z",
      operationalNote: "Primary city. No changes needed.",
      history: [{ id: "sysc-019-h1", actor: "David Cole", action: "Activated", timestamp: "2025-10-01T08:30:00Z", note: "Activated as part of Kenya launch." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-020",
      kind: "region",
      name: "Dubai",
      slug: "dubai",
      description: "Primary city in UAE. Focus area for premium stay and transfer inventory.",
      status: "active",
      category: null, area: null, rolloutPercent: null,
      regionType: "city", parentId: "sysc-018", parentSlug: "uae",
      timezone: "Asia/Dubai", currency: "AED",
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 51,
      updatedBy: "David Cole", updatedAt: "2025-12-15T10:30:00Z",
      operationalNote: "Active city in UAE expansion.",
      history: [{ id: "sysc-020-h1", actor: "David Cole", action: "Activated", timestamp: "2025-12-15T10:30:00Z", note: "Activated with UAE launch." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-021",
      kind: "region",
      name: "Nairobi CBD",
      slug: "nairobi-cbd",
      description: "Central business district of Nairobi. High-demand service area for short transfers and stays.",
      status: "draft",
      category: null, area: null, rolloutPercent: null,
      regionType: "service_area", parentId: "sysc-019", parentSlug: "nairobi",
      timezone: "Africa/Nairobi", currency: "KES",
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 0,
      updatedBy: "Amina Bello", updatedAt: "2026-02-20T09:00:00Z",
      operationalNote: "Draft service area. Requires supply team sign-off before activation.",
      history: [{ id: "sysc-021-h1", actor: "Amina Bello", action: "Created draft", timestamp: "2026-02-20T09:00:00Z", note: "Added after supply team identified high-demand corridor." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-022",
      kind: "region",
      name: "Dubai Marina",
      slug: "dubai-marina",
      description: "Premium waterfront service area in Dubai with high concentration of stays and transfer demand.",
      status: "active",
      category: null, area: null, rolloutPercent: null,
      regionType: "service_area", parentId: "sysc-020", parentSlug: "dubai",
      timezone: "Asia/Dubai", currency: "AED",
      templateKind: null, templateScope: null,
      contentKind: null, contentVersion: null,
      usageCount: 28,
      updatedBy: "David Cole", updatedAt: "2026-01-05T11:00:00Z",
      operationalNote: "Active service area. Strong booking volume.",
      history: [{ id: "sysc-022-h1", actor: "David Cole", action: "Activated", timestamp: "2026-01-05T11:00:00Z", note: "Activated after partner density confirmed for Dubai Marina." }],
      latestAuditRecord: null,
    },

    // ── Moderation templates ─────────────────────────────────────────────────
    {
      id: "sysc-023",
      kind: "template",
      name: "Listing Rejected: Insufficient Photos",
      slug: "listing-rejected-insufficient-photos",
      description: "Rejection message for listings that do not meet the minimum photo quality or quantity standards.",
      status: "active",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: "rejection", templateScope: "listing",
      contentKind: null, contentVersion: null,
      usageCount: 47,
      updatedBy: "David Cole", updatedAt: "2025-11-12T10:00:00Z",
      operationalNote: "Most-used listing rejection template. Keep stable.",
      history: [{ id: "sysc-023-h1", actor: "David Cole", action: "Published", timestamp: "2025-11-12T10:00:00Z", note: "Published after moderation team review." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-024",
      kind: "template",
      name: "Partner Suspended: Terms Violation",
      slug: "partner-suspended-terms-violation",
      description: "Suspension notice sent when a partner account is suspended for a confirmed terms of service violation.",
      status: "active",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: "suspension", templateScope: "partner",
      contentKind: null, contentVersion: null,
      usageCount: 12,
      updatedBy: "Amina Bello", updatedAt: "2025-11-20T14:00:00Z",
      operationalNote: "Active. Used sparingly — review before applying.",
      history: [{ id: "sysc-024-h1", actor: "Amina Bello", action: "Published", timestamp: "2025-11-20T14:00:00Z", note: "Published after legal reviewed the terms violation language." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-025",
      kind: "template",
      name: "Verification: Request Additional Documents",
      slug: "verification-request-additional-docs",
      description: "Document request sent to partners during verification review when supporting materials are incomplete.",
      status: "active",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: "request_docs", templateScope: "verification",
      contentKind: null, contentVersion: null,
      usageCount: 31,
      updatedBy: "David Cole", updatedAt: "2025-12-01T09:00:00Z",
      operationalNote: "Active. Core verification workflow template.",
      history: [{ id: "sysc-025-h1", actor: "David Cole", action: "Published", timestamp: "2025-12-01T09:00:00Z", note: "Published for verification review team use." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-026",
      kind: "template",
      name: "Listing: Send Back for Corrections",
      slug: "listing-send-back-corrections",
      description: "Correction request for listings with minor issues that can be fixed and resubmitted without full rejection.",
      status: "draft",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: "send_back", templateScope: "listing",
      contentKind: null, contentVersion: null,
      usageCount: 0,
      updatedBy: "Amina Bello", updatedAt: "2026-02-28T11:00:00Z",
      operationalNote: "Draft. Needs moderation team review before publishing.",
      history: [{ id: "sysc-026-h1", actor: "Amina Bello", action: "Created draft", timestamp: "2026-02-28T11:00:00Z", note: "Added to reduce full rejections for fixable listing issues." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-027",
      kind: "template",
      name: "API Client: Rejected Due to Risk",
      slug: "api-client-rejected-risk",
      description: "Rejection notice for API client applications that were declined due to elevated risk signals.",
      status: "archived",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: "rejection", templateScope: "api_client",
      contentKind: null, contentVersion: null,
      usageCount: 3,
      updatedBy: "Amina Bello", updatedAt: "2026-03-08T15:00:00Z",
      operationalNote: "Archived. Replaced by a more specific risk-rejection template.",
      history: [{ id: "sysc-027-h1", actor: "Amina Bello", action: "Archived", timestamp: "2026-03-08T15:00:00Z", note: "Archived after replacement template published." }],
      latestAuditRecord: null,
    },

    // ── Static content ───────────────────────────────────────────────────────
    {
      id: "sysc-028",
      kind: "content",
      name: "Partner Terms of Service v3.1",
      slug: "partner-terms-v3-1",
      description: "Current partner terms of service governing platform usage, listing standards, and settlement obligations.",
      status: "published",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: "terms", contentVersion: "3.1",
      usageCount: 0,
      updatedBy: "Amina Bello", updatedAt: "2026-01-10T09:00:00Z",
      operationalNote: "Live version. Do not archive without publishing a replacement.",
      history: [{ id: "sysc-028-h1", actor: "Amina Bello", action: "Published", timestamp: "2026-01-10T09:00:00Z", note: "Published v3.1 after legal sign-off on updated settlement obligation language." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-029",
      kind: "content",
      name: "Data Privacy Policy v2.0",
      slug: "data-privacy-policy-v2",
      description: "Current data privacy and processing policy for partner data under the TravelMate platform.",
      status: "published",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: "policy", contentVersion: "2.0",
      usageCount: 0,
      updatedBy: "Amina Bello", updatedAt: "2025-12-20T10:00:00Z",
      operationalNote: "Live version. GDPR compliance confirmed.",
      history: [{ id: "sysc-029-h1", actor: "Amina Bello", action: "Published", timestamp: "2025-12-20T10:00:00Z", note: "Published v2.0 after DPO review and compliance sign-off." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-030",
      kind: "content",
      name: "Getting Started with TravelMate Partner App",
      slug: "getting-started-partner-app",
      description: "Onboarding help guide covering account setup, listing submission, and first booking steps.",
      status: "published",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: "help_doc", contentVersion: "1.3",
      usageCount: 0,
      updatedBy: "David Cole", updatedAt: "2026-02-01T09:00:00Z",
      operationalNote: "Live. Updated for new onboarding flow.",
      history: [{ id: "sysc-030-h1", actor: "David Cole", action: "Published", timestamp: "2026-02-01T09:00:00Z", note: "Updated to v1.3 for new partner onboarding flow." }],
      latestAuditRecord: null,
    },
    {
      id: "sysc-031",
      kind: "content",
      name: "Platform Maintenance Schedule Update",
      slug: "platform-maintenance-schedule",
      description: "Announcement covering upcoming scheduled maintenance windows and partner impact guidance.",
      status: "draft",
      category: null, area: null, rolloutPercent: null,
      regionType: null, parentId: null, parentSlug: null, timezone: null, currency: null,
      templateKind: null, templateScope: null,
      contentKind: "announcement", contentVersion: "1.0",
      usageCount: 0,
      updatedBy: "David Cole", updatedAt: "2026-04-10T14:00:00Z",
      operationalNote: "Draft announcement. Pending ops team review before publish.",
      history: [{ id: "sysc-031-h1", actor: "David Cole", action: "Created draft", timestamp: "2026-04-10T14:00:00Z", note: "Created ahead of scheduled Q2 maintenance window." }],
      latestAuditRecord: null,
    },
  ];
}
