import type { PayoutReviewRecord } from "@/modules/payout-review/types";

export function getPayoutReviewRecords(): PayoutReviewRecord[] {
  return [
    {
      id: "payout-001",
      title: "Pending bank-account update after rapid payout change",
      summary: "Partner updated the default bank account inside the 72-hour risk window and settlement remains held until finance completes review.",
      partnerName: "GlobalStays Ltd",
      partnerId: "partner-201",
      country: "NG",
      currency: "NGN",
      region: "Lagos",
      methodType: "bank_account",
      status: "pending",
      nameMatchStatus: "matched",
      holdState: "active",
      settlementReadiness: "review_required",
      isDefault: true,
      maskedSummary: "Acct ******4831",
      submissionSource: "partner_update",
      verificationSubmittedAt: "2026-04-18T09:25:00.000Z",
      lastUpdatedAt: "2026-04-18T09:40:00.000Z",
      reviewOwner: "Tunde Adebayo",
      operationalNote: "Finance hold remains active until the changed account details are approved against the partner ownership record.",
      rejectionReason: undefined,
      riskFlags: [
        {
          id: "risk-001",
          label: "Rapid account change",
          detail: "Default payout method changed 19 hours before the next settlement release window.",
          severity: "high",
          requiresReverification: true,
        },
        {
          id: "risk-002",
          label: "Hold linked to settlement run",
          detail: "Financial operations already blocked the next payout batch until this review clears.",
          severity: "medium",
          requiresReverification: false,
        },
      ],
      linkedContext: [
        { id: "ctx-001", label: "Partner account · GlobalStays Ltd", href: "/partners", statusLabel: "verified", kind: "partner" },
        { id: "ctx-002", label: "Financial operations · held settlement batch", href: "/financial-ops", statusLabel: "hold active", kind: "financial_ops" },
        { id: "ctx-003", label: "Audit trail · payout change submission", href: "/audit-compliance", statusLabel: "pending review", kind: "audit" },
      ],
      sensitiveDetails: {
        accountHolderName: "GlobalStays Ltd",
        bankName: "Providence Bank",
        accountNumber: "0123454831",
        routingCode: "044123456",
        swiftCode: "PROVNGLA",
      },
      activity: [
        {
          id: "act-001",
          title: "Settlement hold placed",
          detail: "Finance placed a settlement hold after the partner changed the default payout account within the risk window.",
          time: "09:40 UTC",
          tone: "warning",
        },
        {
          id: "act-002",
          title: "Payout method updated in partner app",
          detail: "Partner submitted a bank-account update and the verification state moved back to pending.",
          time: "09:25 UTC",
          tone: "info",
        },
      ],
    },
    {
      id: "payout-002",
      title: "Pending mobile-money verification with ownership mismatch",
      summary: "Partner submitted a mobile-money payout method, but the holder details still conflict with the verified business profile.",
      partnerName: "QuickRide Kenya",
      partnerId: "partner-318",
      country: "NG",
      currency: "NGN",
      region: "Abuja",
      methodType: "mobile_money",
      status: "pending",
      nameMatchStatus: "mismatched",
      holdState: "active",
      settlementReadiness: "blocked",
      isDefault: false,
      maskedSummary: "Mobile *******7621",
      submissionSource: "partner_self_service",
      verificationSubmittedAt: "2026-04-17T14:10:00.000Z",
      lastUpdatedAt: "2026-04-17T14:45:00.000Z",
      reviewOwner: "Tunde Adebayo",
      operationalNote: "Ownership mismatch still needs a clear rejection or re-verification instruction before settlement can resume.",
      rejectionReason: undefined,
      riskFlags: [
        {
          id: "risk-003",
          label: "Ownership mismatch",
          detail: "Account holder entered in the partner app does not match the verified business registration.",
          severity: "critical",
          requiresReverification: false,
        },
      ],
      linkedContext: [
        { id: "ctx-004", label: "Partner account · QuickRide Kenya", href: "/partners", statusLabel: "verified", kind: "partner" },
        { id: "ctx-005", label: "Support incident · payout verification callback", href: "/support-incidents", statusLabel: "monitoring", kind: "support" },
        { id: "ctx-006", label: "Audit trail · OTP verification attempt", href: "/audit-compliance", statusLabel: "mismatch", kind: "audit" },
      ],
      sensitiveDetails: {
        accountHolderName: "Amina Travel Collections",
        mobileMoneyProvider: "PalmPay",
        mobileNumber: "+2348013377621",
      },
      activity: [
        {
          id: "act-003",
          title: "Ownership mismatch flagged",
          detail: "Name-match check failed after the partner submitted the mobile-money payout method.",
          time: "14:45 UTC",
          tone: "danger",
        },
        {
          id: "act-004",
          title: "Payout method submitted",
          detail: "Partner created a new payout method and OTP verification completed with a mismatch outcome.",
          time: "14:10 UTC",
          tone: "info",
        },
      ],
    },
    {
      id: "payout-003",
      title: "Verified bank account under post-approval fraud review",
      summary: "A previously verified payout method remains active, but a suspicious change pattern means finance may reverify and place a fresh hold.",
      partnerName: "Savannah Suites",
      partnerId: "partner-144",
      country: "GB",
      currency: "GBP",
      region: "London",
      methodType: "bank_account",
      status: "verified",
      nameMatchStatus: "matched",
      holdState: "clear",
      settlementReadiness: "ready",
      isDefault: true,
      maskedSummary: "Acct ********9017",
      submissionSource: "partner_update",
      verificationSubmittedAt: "2026-04-15T10:00:00.000Z",
      verifiedAt: "2026-04-15T10:25:00.000Z",
      lastUpdatedAt: "2026-04-19T06:10:00.000Z",
      reviewOwner: "Tunde Adebayo",
      operationalNote: "The payout method is verified, but finance is monitoring for rapid location and payout-detail changes across linked regions.",
      rejectionReason: undefined,
      riskFlags: [
        {
          id: "risk-004",
          label: "Suspicious update pattern",
          detail: "Two payout-detail edits and one default-method switch were recorded across linked properties in 48 hours.",
          severity: "high",
          requiresReverification: true,
        },
      ],
      linkedContext: [
        { id: "ctx-007", label: "Financial operations · payout ready", href: "/financial-ops", statusLabel: "ready", kind: "financial_ops" },
        { id: "ctx-008", label: "Partner account · Savannah Suites", href: "/partners", statusLabel: "verified", kind: "partner" },
        { id: "ctx-009", label: "Audit trail · verification complete", href: "/audit-compliance", statusLabel: "verified", kind: "audit" },
      ],
      sensitiveDetails: {
        accountHolderName: "Savannah Suites Holdings",
        bankName: "Crown Merchant Bank",
        accountNumber: "442211889017",
        iban: "GB82WEST12345698765432",
        swiftCode: "CMBKGB2L",
      },
      activity: [
        {
          id: "act-005",
          title: "Fraud signal reopened",
          detail: "Risk monitoring reopened the payout review after repeated payout-detail changes across the partner account.",
          time: "06:10 UTC",
          tone: "warning",
        },
        {
          id: "act-006",
          title: "Payout method verified",
          detail: "Finance previously approved this bank account and released the settlement gate.",
          time: "10:25 UTC",
          tone: "success",
        },
      ],
    },
  ];
}
