import type { CommercialRuleRecord } from "@/modules/commercial-controls/types";

export function getCommercialControlRecords(): CommercialRuleRecord[] {
  return [
    {
      id: "commercial-rule-001",
      title: "Global stay marketplace base commission",
      ruleType: "commission",
      scope: "global",
      region: "All markets",
      status: "active",
      commissionRatePercent: 14,
      serviceFeeFlatAmount: 3,
      effectiveDate: "2026-04-15",
      lastUpdatedAt: "2026-04-15T09:20:00.000Z",
      lastUpdatedBy: "Tunde Adebayo",
      summary: "Primary commission rule applied to marketplace stay supply where no regional or partner override exists.",
      downstreamImpactSummary: "Feeds settlement previews, partner payout statements, and partner-side pricing disclosures for 128 stay partners.",
      operationalNote: "Keep this rule aligned with the active marketplace margin plan for stay inventory.",
      partnerSettings: [
        {
          id: "partner-setting-001",
          partnerName: "Lagos Stay Collective",
          region: "Nigeria",
          commissionRatePercent: 14,
          serviceFeeFlatAmount: 3,
          settlementCadenceLabel: "Weekly settlement",
          overrideReason: "Inherits current global default.",
        },
        {
          id: "partner-setting-002",
          partnerName: "Cape Urban Suites",
          region: "South Africa",
          commissionRatePercent: 14,
          serviceFeeFlatAmount: 3,
          settlementCadenceLabel: "Weekly settlement",
          overrideReason: "Inherits current global default.",
        },
      ],
      manualAdjustmentHistory: [
        {
          id: "adjustment-001",
          partnerName: "Lagos Stay Collective",
          direction: "credit",
          amount: 120,
          currency: "USD",
          reason: "Promotional rebate true-up",
          note: "Applied temporary rebate to align February campaign promise.",
          createdAt: "2026-04-16 08:30 UTC",
          createdBy: "Tunde Adebayo",
        },
      ],
      history: [
        {
          id: "history-001",
          actor: "Tunde Adebayo",
          action: "Commission rule updated",
          timestamp: "15/04/2026 09:20 UTC",
          note: "Raised stay commission from 13.5% to 14% for Q2 margin stabilization.",
        },
      ],
      latestAuditRecord: null,
    },
    {
      id: "commercial-rule-002",
      title: "East Africa transfer service fee override",
      ruleType: "service_fee",
      scope: "region",
      region: "East Africa",
      status: "scheduled",
      commissionRatePercent: 10,
      serviceFeeFlatAmount: 5,
      effectiveDate: "2026-05-01",
      lastUpdatedAt: "2026-04-12T14:05:00.000Z",
      lastUpdatedBy: "Amina Bello",
      summary: "Scheduled service-fee adjustment for transfer partners covering airport and hotel transfer corridors in East Africa.",
      downstreamImpactSummary: "Will update transfer checkout fee disclosures and settlement calculations for 42 regional transfer partners on May 1.",
      operationalNote: "Validate partner notification timing before the rule becomes effective.",
      partnerSettings: [
        {
          id: "partner-setting-003",
          partnerName: "Safari Ride Network",
          region: "Kenya",
          commissionRatePercent: 10,
          serviceFeeFlatAmount: 5,
          settlementCadenceLabel: "Bi-weekly settlement",
          overrideReason: "Regional transfer override for East Africa service fee uplift.",
        },
        {
          id: "partner-setting-004",
          partnerName: "Kampala City Transfers",
          region: "Uganda",
          commissionRatePercent: 10,
          serviceFeeFlatAmount: 5,
          settlementCadenceLabel: "Bi-weekly settlement",
          overrideReason: "Regional transfer override for East Africa service fee uplift.",
        },
      ],
      manualAdjustmentHistory: [
        {
          id: "adjustment-002",
          partnerName: "Safari Ride Network",
          direction: "debit",
          amount: 75,
          currency: "USD",
          reason: "Incorrect fee application reversal",
          note: "Recovered over-credit issued during transfer fee pilot clean-up.",
          createdAt: "2026-04-13 11:45 UTC",
          createdBy: "Amina Bello",
        },
      ],
      history: [
        {
          id: "history-002",
          actor: "Amina Bello",
          action: "Service fee rule scheduled",
          timestamp: "12/04/2026 14:05 UTC",
          note: "Prepared East Africa transfer service-fee uplift pending partner communication.",
        },
      ],
      latestAuditRecord: null,
    },
    {
      id: "commercial-rule-003",
      title: "VoyageStack enterprise API partner override",
      ruleType: "commission",
      scope: "partner",
      region: "Nigeria",
      status: "active",
      commissionRatePercent: 8.5,
      serviceFeeFlatAmount: 2,
      effectiveDate: "2026-04-10",
      lastUpdatedAt: "2026-04-10T16:00:00.000Z",
      lastUpdatedBy: "Tunde Adebayo",
      summary: "Partner-specific override supporting enterprise API growth commitments for VoyageStack Labs.",
      downstreamImpactSummary: "Applies only to VoyageStack Labs and is mirrored into finance review notes for enterprise account management.",
      operationalNote: "Keep override visible because it affects reconciliation expectations for a strategic account.",
      partnerSettings: [
        {
          id: "partner-setting-005",
          partnerName: "VoyageStack Labs",
          region: "Nigeria",
          commissionRatePercent: 8.5,
          serviceFeeFlatAmount: 2,
          settlementCadenceLabel: "Weekly settlement",
          overrideReason: "Strategic enterprise commercial commitment.",
        },
      ],
      manualAdjustmentHistory: [],
      history: [
        {
          id: "history-003",
          actor: "Tunde Adebayo",
          action: "Partner override approved",
          timestamp: "10/04/2026 16:00 UTC",
          note: "Applied strategic commercial override for enterprise API growth account.",
        },
      ],
      latestAuditRecord: null,
    },
  ];
}
