import type { NotificationRecord } from "@/modules/notifications/types";

export function getNotificationRecords(): NotificationRecord[] {
  return [
    {
      id: "notification-001",
      title: "Updated payout statement timeline for verified partners",
      body: "We have updated the payout statement publishing timeline for verified partners. Statements will now appear every Tuesday by 10:00 UTC.",
      kind: "broadcast",
      status: "draft",
      audienceSegment: "verified_partners",
      region: null,
      channels: ["email", "in_app"],
      targetPartnerCount: 184,
      createdAt: "2026-04-18T10:20:00.000Z",
      createdBy: "Maya Singh",
      summary: "Prepared broadcast for verified partners about revised payout-statement timing.",
      deliveryMetadata: null,
      operationalNote: "Coordinate with finance before sending broad payout communications.",
      source: "admin_outbound",
      routing: {},
      history: [
        {
          id: "notification-history-001",
          actor: "Maya Singh",
          action: "Draft prepared",
          timestamp: "18/04/2026 10:20 UTC",
          note: "Prepared verified-partner broadcast pending final finance review.",
        },
      ],
      latestAuditRecord: null,
    },
    {
      id: "notification-002",
      title: "East Africa transfer fee policy notice",
      body: "Transfer partners in East Africa will see the new service-fee policy take effect on May 1. Review your partner dashboard for updated settlement previews.",
      kind: "transactional",
      status: "sent",
      audienceSegment: "region",
      region: "East Africa",
      channels: ["email", "in_app"],
      targetPartnerCount: 42,
      createdAt: "2026-04-17T08:15:00.000Z",
      createdBy: "Amina Bello",
      summary: "Sent transactional notice to East Africa transfer partners about scheduled fee-policy updates.",
      deliveryMetadata: {
        deliveredCount: 41,
        failedCount: 1,
        channels: ["email", "in_app"],
        targetSummary: "East Africa transfer partners",
        sentAt: "17/04/2026 08:40 UTC",
        dispatchStatus: "completed",
        estimatedTargetCount: 42,
        isEstimated: false,
      },
      operationalNote: "One email bounce remains open with support for Safari Ride Network.",
      source: "admin_outbound",
      routing: {},
      history: [
        {
          id: "notification-history-002",
          actor: "Amina Bello",
          action: "Message sent",
          timestamp: "17/04/2026 08:40 UTC",
          note: "Transactional notice sent to East Africa transfer partners ahead of the fee-policy change.",
        },
      ],
      latestAuditRecord: null,
    },
    {
      id: "notification-003",
      title: "Direct outreach for API key rotation reminder",
      body: "Please rotate your API key before April 30 to avoid access interruptions. Contact support if you need help updating your integration.",
      kind: "direct",
      status: "sent",
      audienceSegment: "api_clients",
      region: null,
      channels: ["email"],
      targetPartnerCount: 1,
      createdAt: "2026-04-16T15:00:00.000Z",
      createdBy: "David Cole",
      summary: "Direct reminder sent to an API client regarding pending key-rotation requirements.",
      deliveryMetadata: {
        deliveredCount: 1,
        failedCount: 0,
        channels: ["email"],
        targetSummary: "VoyageStack Labs",
        sentAt: "16/04/2026 15:02 UTC",
        dispatchStatus: "completed",
        estimatedTargetCount: 1,
        isEstimated: false,
      },
      operationalNote: "Keep support looped in if the client reports integration blockers.",
      source: "admin_outbound",
      routing: {},
      history: [
        {
          id: "notification-history-003",
          actor: "David Cole",
          action: "Message sent",
          timestamp: "16/04/2026 15:02 UTC",
          note: "Direct reminder sent after API governance review.",
        },
      ],
      latestAuditRecord: null,
    },
  ];
}
