import type { CatalogIssueRecord, TaxonomyRuleRecord } from "@/modules/catalog-controls/types";

export const catalogControlsSeed: CatalogIssueRecord[] = [
  {
    id: "catalog-issue-001",
    listingId: "listing-stay-004",
    listingTitle: "Harbour Crest Suites Annex",
    partnerName: "Amina Yusuf",
    businessName: "North Harbour Stays",
    kind: "stay",
    issueType: "duplicate",
    status: "open",
    severity: "high",
    locationLabel: "Lagos, Nigeria",
    submittedAt: "2026-04-17T08:40:00.000Z",
    lastReviewedAt: "2026-04-17T09:05:00.000Z",
    completenessScore: 88,
    summary: "Duplicate signature overlaps with an existing marina stay submission and risks duplicate catalog exposure.",
    missingRequiredFields: [],
    duplicateWarnings: ['Possible duplicate stay found: "North Harbour Marina Suites" in Lagos.'],
    taxonomySuggestions: [],
    geoCheck: {
      status: "match",
      summary: "Geo markers align with the existing Lagos waterfront cluster.",
    },
    policyFlags: [],
    operationalNote: "Confirm whether the annex is genuinely separate inventory before allowing it through.",
    history: [
      {
        id: "catalog-history-1",
        actor: "System",
        action: "Duplicate signal created",
        timestamp: "2026-04-17 09:05 UTC",
        note: "Partner-side quality checks emitted a duplicate warning during submission.",
      },
    ],
  },
  {
    id: "catalog-issue-002",
    listingId: "listing-transfer-004",
    listingTitle: "Accra Gold Line Executive Shuttle",
    partnerName: "David Mensah",
    businessName: "Accra Executive Transfers",
    kind: "transfer",
    issueType: "taxonomy",
    status: "open",
    severity: "medium",
    locationLabel: "Accra, Ghana",
    submittedAt: "2026-04-17T06:20:00.000Z",
    lastReviewedAt: "2026-04-17T07:10:00.000Z",
    completenessScore: 82,
    summary: "Transfer inventory uses non-standard taxonomy values that should be normalized before catalog publication.",
    missingRequiredFields: ["Description"],
    duplicateWarnings: [],
    taxonomySuggestions: [
      {
        field: "Vehicle Class",
        currentValue: "Executive Gold",
        suggestedValue: "Executive SUV",
        reason: "Maps to the approved transfer taxonomy used across partner_app quality checks.",
      },
      {
        field: "Transfer Type",
        currentValue: "Airport Gold Route",
        suggestedValue: "Airport pickup",
        reason: "Standardized transfer type improves routing filters and partner-side consistency.",
      },
    ],
    geoCheck: {
      status: "match",
      summary: "Coverage polygon matches the approved Accra airport service area.",
    },
    policyFlags: [],
    operationalNote: "Normalize the transfer taxonomy before it reaches search filters.",
    history: [
      {
        id: "catalog-history-2",
        actor: "System",
        action: "Taxonomy gap detected",
        timestamp: "2026-04-17 07:10 UTC",
        note: "Catalog standardization flagged non-canonical transfer labels.",
      },
    ],
  },
  {
    id: "catalog-issue-003",
    listingId: "listing-stay-005",
    listingTitle: "Savannah River Camp Villas",
    partnerName: "Maya Patel",
    businessName: "Savannah Retreat Collections",
    kind: "stay",
    issueType: "geo",
    status: "in_review",
    severity: "high",
    locationLabel: "Nairobi, Kenya",
    submittedAt: "2026-04-16T14:15:00.000Z",
    lastReviewedAt: "2026-04-17T10:25:00.000Z",
    completenessScore: 91,
    summary: "Submitted stay location points to a conservation boundary outside the configured Nairobi service area.",
    missingRequiredFields: [],
    duplicateWarnings: [],
    taxonomySuggestions: [],
    geoCheck: {
      status: "mismatch",
      summary: "Coordinates indicate Naivasha service area while the listing claims Nairobi river district.",
      suggestedCity: "Naivasha",
      suggestedCountry: "Kenya",
    },
    policyFlags: [],
    operationalNote: "Check whether the partner selected the wrong city or uploaded the wrong map pin.",
    history: [
      {
        id: "catalog-history-3",
        actor: "Operations Admin",
        action: "Geo mismatch escalated",
        timestamp: "2026-04-17 10:25 UTC",
        note: "Issue moved to in-review after service-area mismatch crossed threshold.",
      },
    ],
  },
  {
    id: "catalog-issue-004",
    listingId: "listing-transfer-005",
    listingTitle: "Night Shield City Transfer",
    partnerName: "Kwame Osei",
    businessName: "Night Route Mobility",
    kind: "transfer",
    issueType: "policy",
    status: "open",
    severity: "critical",
    locationLabel: "Accra, Ghana",
    submittedAt: "2026-04-17T05:45:00.000Z",
    lastReviewedAt: "2026-04-17T05:55:00.000Z",
    completenessScore: 76,
    summary: "Transfer copy includes unsupported security and escort guarantees that violate catalog policy language.",
    missingRequiredFields: ["Features"],
    duplicateWarnings: [],
    taxonomySuggestions: [],
    geoCheck: {
      status: "match",
      summary: "Route and area align with the configured city-transfer boundaries.",
    },
    policyFlags: [
      "Unsupported safety guarantee in title and summary.",
      "Escort-service claim requires compliance review before listing can appear in catalog.",
    ],
    operationalNote: "Resolve content policy exception before this transfer returns to moderation.",
    history: [
      {
        id: "catalog-history-4",
        actor: "System",
        action: "Policy exception detected",
        timestamp: "2026-04-17 05:55 UTC",
        note: "Content policy checks flagged unsupported safety guarantees in transfer marketing copy.",
      },
    ],
  },
];

export function getCatalogIssueRecords() {
  return catalogControlsSeed;
}

export const taxonomyRuleSeed: TaxonomyRuleRecord[] = [
  {
    id: "taxonomy-rule-001",
    field: "Vehicle Class",
    currentValue: "Executive Gold",
    normalizedValue: "Executive SUV",
    scope: "transfer",
    usageCount: 4,
    lastUpdatedAt: "2026-04-16T13:00:00.000Z",
    lastUpdatedBy: "Catalog System",
  },
  {
    id: "taxonomy-rule-002",
    field: "Transfer Type",
    currentValue: "Airport Gold Route",
    normalizedValue: "Airport pickup",
    scope: "transfer",
    usageCount: 3,
    lastUpdatedAt: "2026-04-16T13:20:00.000Z",
    lastUpdatedBy: "Catalog System",
  },
  {
    id: "taxonomy-rule-003",
    field: "Property Type",
    currentValue: "Boutique Marina Annex",
    normalizedValue: "Boutique hotel",
    scope: "stay",
    usageCount: 2,
    lastUpdatedAt: "2026-04-15T15:40:00.000Z",
    lastUpdatedBy: "Operations Admin",
  },
];

export function getTaxonomyRuleRecords() {
  return taxonomyRuleSeed;
}
