import type { ApiMonitoringRecord } from "@/modules/api-monitoring/types";

export const apiMonitoringSeed: ApiMonitoringRecord[] = [
  {
    id: "api-anomaly-001",
    title: "Latency spike on availability search",
    category: "latency",
    status: "open",
    incidentState: "not_open",
    severity: "high",
    clientId: "api-client-003",
    clientName: "SkyPath Consolidators",
    endpointLabel: "GET /v1/inventory/search",
    region: "Kenya",
    summary: "Search latency has climbed above the operational threshold for enterprise itinerary enrichment traffic.",
    anomalyReason: "P95 latency exceeded 1100ms for 30 minutes while request volume stayed above the enterprise baseline.",
    firstDetectedAt: "2026-04-18T06:45:00.000Z",
    lastSeenAt: "2026-04-19T07:20:00.000Z",
    currentTrafficPerMinute: 680,
    p95LatencyMs: 1180,
    errorRatePercent: 2.8,
    rateLimitViolations24h: 6,
    impactedEndpoints: [
      {
        endpointLabel: "GET /v1/inventory/search",
        requestCount24h: 48200,
        errorRatePercent: 2.8,
        p95LatencyMs: 1180,
        rateLimitViolations24h: 6,
      },
      {
        endpointLabel: "GET /v1/catalog/transfers",
        requestCount24h: 19640,
        errorRatePercent: 1.4,
        p95LatencyMs: 820,
        rateLimitViolations24h: 1,
      },
    ],
    accessHistory: [
      {
        id: "api-activity-1",
        timestamp: "2026-04-19 07:12 UTC",
        actorLabel: "SkyPath Consolidators",
        event: "Burst traffic",
        summary: "Search endpoint sustained >650 requests/minute across itinerary refresh jobs.",
      },
      {
        id: "api-activity-2",
        timestamp: "2026-04-19 06:58 UTC",
        actorLabel: "System",
        event: "Latency threshold crossed",
        summary: "P95 latency crossed the high-risk threshold and anomaly remained open.",
      },
    ],
    operationalNote: "Confirm whether the client rollout changed polling cadence before queuing containment.",
    governanceRecommendation: "Investigate sustained polling and prepare containment if latency remains above threshold.",
    clientLink: {
      href: "/api-clients?client=api-client-003",
      label: "Open API client governance record",
      summary: "Link this anomaly to the SkyPath Consolidators governance record for key and quota review.",
    },
    history: [
      {
        id: "api-monitoring-history-1",
        actor: "System",
        action: "Latency anomaly created",
        timestamp: "2026-04-19 06:58 UTC",
        note: "Automated monitoring opened this anomaly after sustained P95 latency threshold breach.",
      },
    ],
  },
  {
    id: "api-anomaly-002",
    title: "Rate-limit violation burst on partner export",
    category: "rate_limit",
    status: "investigating",
    incidentState: "open",
    severity: "critical",
    clientId: "api-client-002",
    clientName: "RouteFlow Integrations",
    endpointLabel: "GET /v1/partners/export",
    region: "Ghana",
    summary: "Client export jobs repeatedly exceeded allowed request cadence and triggered sustained rate-limit violations.",
    anomalyReason: "The client crossed the minute-level rate cap 43 times in the last 24 hours on a sensitive export endpoint.",
    firstDetectedAt: "2026-04-18T10:10:00.000Z",
    lastSeenAt: "2026-04-19T07:05:00.000Z",
    currentTrafficPerMinute: 185,
    p95LatencyMs: 640,
    errorRatePercent: 6.2,
    rateLimitViolations24h: 43,
    impactedEndpoints: [
      {
        endpointLabel: "GET /v1/partners/export",
        requestCount24h: 8400,
        errorRatePercent: 6.2,
        p95LatencyMs: 640,
        rateLimitViolations24h: 43,
      },
    ],
    accessHistory: [
      {
        id: "api-activity-3",
        timestamp: "2026-04-19 07:05 UTC",
        actorLabel: "RouteFlow Integrations",
        event: "Rate-limit violation burst",
        summary: "Background export sync retried aggressively after 429 responses.",
      },
      {
        id: "api-activity-4",
        timestamp: "2026-04-18 21:18 UTC",
        actorLabel: "Operations Admin",
        event: "Monitoring review started",
        summary: "Operations began manual investigation after repeated export-threshold violations.",
      },
    ],
    operationalNote: "Escalate if the client keeps retrying without backoff after the next observation window.",
    governanceRecommendation: "Open an incident or queue client containment if export retries continue without backoff.",
    clientLink: {
      href: "/api-clients?client=api-client-002",
      label: "Open API client governance record",
      summary: "RouteFlow Integrations should stay linked to this alert for revoke/block review if abuse persists.",
      lastLinkedAction: "open_incident",
    },
    history: [
      {
        id: "api-monitoring-history-2",
        actor: "System",
        action: "Rate-limit anomaly created",
        timestamp: "2026-04-18 10:12 UTC",
        note: "Export endpoint crossed sustained rate-limit thresholds.",
      },
      {
        id: "api-monitoring-history-3",
        actor: "Operations Admin",
        action: "Alert acknowledged",
        timestamp: "2026-04-18 21:18 UTC",
        note: "Investigation started while export retries remained active.",
      },
    ],
  },
  {
    id: "api-anomaly-003",
    title: "Error burst on booking read access",
    category: "errors",
    status: "contained",
    incidentState: "not_open",
    severity: "medium",
    clientId: "api-client-001",
    clientName: "VoyageStack Labs",
    endpointLabel: "GET /v1/bookings",
    region: "Nigeria",
    summary: "A temporary error burst appeared after a newly approved client tested booking read access with malformed filters.",
    anomalyReason: "5xx and validation error mix rose above baseline until client traffic cooled after investigation and guidance.",
    firstDetectedAt: "2026-04-18T15:00:00.000Z",
    lastSeenAt: "2026-04-18T16:10:00.000Z",
    currentTrafficPerMinute: 12,
    p95LatencyMs: 320,
    errorRatePercent: 1.2,
    rateLimitViolations24h: 0,
    impactedEndpoints: [
      {
        endpointLabel: "GET /v1/bookings",
        requestCount24h: 920,
        errorRatePercent: 1.2,
        p95LatencyMs: 320,
        rateLimitViolations24h: 0,
      },
    ],
    accessHistory: [
      {
        id: "api-activity-5",
        timestamp: "2026-04-18 16:05 UTC",
        actorLabel: "Operations Admin",
        event: "Containment queued",
        summary: "Temporary client review handoff prepared while malformed filter traffic subsided.",
      },
      {
        id: "api-activity-6",
        timestamp: "2026-04-18 15:10 UTC",
        actorLabel: "VoyageStack Labs",
        event: "Validation failures",
        summary: "Client repeatedly called bookings read with unsupported compound filters.",
      },
    ],
    operationalNote: "Contained for now; keep the handoff linked to API client governance if errors reappear.",
    governanceRecommendation: "Keep this contained record linked to client history for future abuse investigation.",
    clientLink: {
      href: "/api-clients?client=api-client-001",
      label: "Open API client governance record",
      summary: "VoyageStack Labs remains linked for follow-up if malformed bookings queries return.",
      lastLinkedAction: "queue_client_containment",
    },
    history: [
      {
        id: "api-monitoring-history-4",
        actor: "Operations Admin",
        action: "Containment queued",
        timestamp: "2026-04-18 16:05 UTC",
        note: "Prepared a client governance handoff after the error burst subsided.",
      },
    ],
  },
];

export function getApiMonitoringRecords() {
  return apiMonitoringSeed;
}
