import type { SupportIncidentRecord } from "@/modules/support-incidents/types";

export function getSupportIncidentRecords(): SupportIncidentRecord[] {
  return [
    {
      id: "sup-001",
      title: "Partner cannot reopen locked account after ID revalidation",
      summary: "A verified Nairobi stay partner passed revalidation, but the back-office unlock did not restore access in the partner app.",
      partnerName: "Safari Crest Residences",
      owner: "Maya Singh",
      queue: "partner_support",
      severity: "high",
      status: "open",
      incidentState: "none",
      issueType: "partner_access",
      channel: "email",
      region: "East Africa",
      responseDeadline: "2026-04-19T18:00:00Z",
      lastUpdatedAt: "2026-04-19T11:25:00Z",
      openedAt: "2026-04-19T09:10:00Z",
      escalationTeam: "operations",
      operationalNote: "Partner reports unlock email was received, but session restore still fails on the dashboard.",
      linkedContext: [
        { id: "ctx-001", label: "Partner account · Safari Crest Residences", href: "/partners?partner=partner-001", statusLabel: "locked", kind: "partner" },
        { id: "ctx-002", label: "Verification review · revalidation packet", href: "/verification-review?case=vr-102", statusLabel: "approved", kind: "verification" },
      ],
      diagnostics: [],
      activity: [
        {
          id: "sup-001-act-1",
          title: "Case opened from partner email",
          detail: "Support captured the account-access complaint and linked the verification packet for quick review.",
          time: "09:10 UTC",
          tone: "info",
        },
      ],
    },
    {
      id: "sup-002",
      title: "Refund dispute linked to cancelled airport transfer",
      summary: "Partner claims the customer refund was processed, but the platform still shows the refund follow-up as unresolved.",
      partnerName: "MetroRide Executive",
      owner: "Tunde Adebayo",
      queue: "financial_followup",
      severity: "critical",
      status: "monitoring",
      incidentState: "active",
      issueType: "refund_followup",
      channel: "phone",
      region: "West Africa",
      responseDeadline: "2026-04-19T15:30:00Z",
      lastUpdatedAt: "2026-04-19T10:50:00Z",
      openedAt: "2026-04-18T16:40:00Z",
      escalationTeam: "finance",
      operationalNote: "Finance requested a masked settlement trace before closing the refund recovery loop.",
      linkedContext: [
        { id: "ctx-003", label: "Financial operations · refund case", href: "/financial-ops", statusLabel: "partner_notified", kind: "settlement" },
        { id: "ctx-004", label: "Partner account · MetroRide Executive", href: "/partners?partner=partner-004", statusLabel: "verified", kind: "partner" },
      ],
      diagnostics: [
        {
          id: "diag-002",
          runAt: "2026-04-19T08:20:00Z",
          actor: "Maya Singh",
          summary: "Safe diagnostics confirmed a queued refund ledger handoff with masked settlement references only.",
          checks: [
            { id: "diag-002-1", label: "Refund workflow", status: "warn", detail: "Refund handoff still waiting on finance reconciliation batch." },
            { id: "diag-002-2", label: "Masked settlement reference", status: "pass", detail: "Settlement trace is available as batch ****1834 with no raw payout fields exposed." },
          ],
        },
      ],
      activity: [
        {
          id: "sup-002-act-1",
          title: "Incident flagged for refund mismatch",
          detail: "Support opened a finance-linked incident after partner and customer refund timelines diverged.",
          time: "16:40 UTC",
          tone: "warning",
        },
      ],
    },
    {
      id: "sup-003",
      title: "Listing edits not reflected after moderation send-back",
      summary: "A Dubai transfer partner resubmitted corrected listing details, but the moderation surface still shows the previous draft.",
      partnerName: "Desert Pearl Transfers",
      owner: "David Cole",
      queue: "incident_response",
      severity: "medium",
      status: "escalated",
      incidentState: "active",
      issueType: "listing_sync",
      channel: "internal",
      region: "Gulf",
      responseDeadline: "2026-04-20T09:00:00Z",
      lastUpdatedAt: "2026-04-19T09:40:00Z",
      openedAt: "2026-04-18T13:00:00Z",
      escalationTeam: "trust",
      operationalNote: "Operations escalated after content updates stayed stale across moderation and partner read surfaces.",
      linkedContext: [
        { id: "ctx-005", label: "Listing moderation · transfer route update", href: "/moderation?record=mod-211", statusLabel: "send_back", kind: "listing" },
        { id: "ctx-006", label: "Partner account · Desert Pearl Transfers", href: "/partners?partner=partner-008", statusLabel: "verified", kind: "partner" },
      ],
      diagnostics: [
        {
          id: "diag-003",
          runAt: "2026-04-19T09:00:00Z",
          actor: "David Cole",
          summary: "Safe diagnostics show moderation replay lag without exposing raw request payloads.",
          checks: [
            { id: "diag-003-1", label: "Moderation sync lag", status: "warn", detail: "Sync replay is delayed by 14 minutes for this listing revision." },
            { id: "diag-003-2", label: "Partner submission receipt", status: "pass", detail: "Corrected submission was accepted and versioned successfully." },
          ],
        },
      ],
      activity: [
        {
          id: "sup-003-act-1",
          title: "Escalated to incident response",
          detail: "Operations escalated the listing-sync issue after the corrected partner draft stayed stale in moderation review.",
          time: "09:40 UTC",
          tone: "danger",
        },
      ],
    },
    {
      id: "sup-004",
      title: "Verification handoff needs partner follow-up note",
      summary: "A reviewer requested support follow-up to coach a partner through document resubmission steps without resetting the case.",
      partnerName: "Lagoon Suites",
      owner: "Ifeoma Okoye",
      queue: "partner_support",
      severity: "low",
      status: "open",
      incidentState: "none",
      issueType: "verification_handoff",
      channel: "in_app",
      region: "West Africa",
      responseDeadline: "2026-04-20T12:00:00Z",
      lastUpdatedAt: "2026-04-19T07:55:00Z",
      openedAt: "2026-04-19T07:50:00Z",
      escalationTeam: "support",
      operationalNote: "Partner needs a calmer explanation of the address-proof requirements before the reviewer resumes the queue.",
      linkedContext: [
        { id: "ctx-007", label: "Verification review · pending resubmission", href: "/verification-review?case=vr-108", statusLabel: "more_info_required", kind: "verification" },
        { id: "ctx-008", label: "Partner account · Lagoon Suites", href: "/partners?partner=partner-010", statusLabel: "pending", kind: "partner" },
      ],
      diagnostics: [],
      activity: [
        {
          id: "sup-004-act-1",
          title: "Reviewer handoff captured",
          detail: "Support received the handoff so the partner can be guided before the review queue is retried.",
          time: "07:50 UTC",
          tone: "neutral",
        },
      ],
    },
  ];
}
